server:
  port: 7071
  
spring:
  application:
    name: name
  cloud:
    config:
      label: master
      profile: dev
  sleuth: 
    sampler: 
       percentage: 1
  zipkin:
    base-url: http://localhost:9411
#      uri: http://localhost:8888/ # single config-servrer configuration
  bus:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server