spring:
  application:
    name: name
  cloud:
    config:
      label: master
      profile: dev
      
#      uri: http://localhost:8888/ # single config-servrer configuration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server