server:
  port: 7070
  
spring:
  application:
    name: name
  cloud:
    config:
      label: master
      profile: dev
  zipkin:
    base-url: http://localhost:9411
#      uri: http://localhost:8888/ # single config-servrer configuration
  bus:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server