server:
  port: 9411

spring:
  application:
    name: zipkin-server
#  cloud:
#    config:
#      name: zipkin
#      service-id: config
#      discovery:
#        enabled: true
#        username: configUser
#        password: configPassword

logging:
  level:
    org:
      springframework:
        web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    region: default
#   registryFetchIntervalSeconds: 5
    
