server:
  port: 8769

spring:
  application:
    name: zuul-server

zuul:
  routes:
    web:
      path: /**
      serviceId: web
    name:
      path: /**
      serviceId: name
    greeting:
      path: /**
      serviceId: greeting
    profile:
      path: /**
      serviceId: profile

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/